@startuml
'https://plantuml.com/sequence-diagram

hide methods
left to right direction


class CenterCoodinator{}

class CSVFile{
+ arrivalDate
+departureDate
}
class CenterPerformance{
+performanceList
+maxSumSublist
+maxSum
+timeInterval
}

CenterCoodinator "*"--"1" CSVFile : "loads into the system" >
CenterCoodinator --> CenterPerformance : "Wants to know"
CSVFile "1"--"1" CenterPerformance :"has it's information treated to become" >


@enduml