@startuml
autonumber
actor "Receptionist" as rec

activate rec
rec -> ":System" : asks to check the user into the waiting room
activate ":System"
":System" --> rec : shows centers for selection
deactivate ":System"

rec -> ":System" : selects vaccination center
activate ":System"
":System" --> rec : shows appointments for relevant time frame
deactivate ":System"

rec -> ":System" : selects user to add to waiting room
activate ":System"
":System" --> rec : informs user is added
deactivate ":System"


deactivate rec

@enduml