@startuml
autonumber
actor "Receptionist" as rcp

activate rcp
rcp -> ":System" : starts registering a new SNS User
activate ":System"
":System" --> rcp : requests data (SNS Number, Phone Number, Email Address, \n Username, Password)
deactivate ":System"

rcp -> ":System" : types requested data
activate ":System"
":System" --> rcp : shows the data and requests a confirmation
deactivate ":System"

rcp -> ":System" : confirms the data
activate ":System"
":System" --> rcp : informs operation success
deactivate ":System"

deactivate rcp

@enduml