@startuml
actor "Admin" as adm
actor "Nurse" as nur
actor "Receptionist" as rcp
actor "User" as user
actor "Center Coordinator" as cc

package System{
   package Registering{
    package RegisteringVaccines{
        usecase UC15 as "Register vaccine type, name and lot number used"
        usecase UC16 as "Register new vaccine"
        usecase UC17 as "Register new vaccine type"
    }
    package RegisteringWork{
        usecase UC07 as "Register center coordinators"
        usecase UC08 as "Register receptionists"
        usecase UC09 as "Register nurses"
        usecase UC05 as "Register centers"
    }
    package RegisteringClients{
        usecase UC06 as "Register SNS users"
        usecase UC11 as "Register the arrival of SNS user"
    }

 }
   package VaccinationProccess{
      usecase UC12 as "Ask SNS user for his number"
      usecase UC13 as "Confirm if that user has a vaccination scheduled for that day and time"
      usecase UC18 as "Monitors the vaccination process and the healthcare center"
   }


package App{

         usecase UC01 as "Schedule vaccination"
         usecase UC03 as "Deliver vaccination certificate"
     package MainInfo{
             usecase UC04 as "Acess all user's health data"
             usecase UC10 as "Configuring and managing the core information"
     }

}



}




left to right direction
user --> (UC01)
user --> (UC06)


adm --> (UC10)
adm --> (UC05)
adm --> (UC06)
adm --> (UC07)
adm --> (UC08)
adm --> (UC09)
adm --> (UC16)
adm --> (UC17)


nur --> (UC03)
nur --> (UC04)
rcp --> (UC11)
rcp --> (UC12)
rcp --> (UC13)
nur --> (UC15)


cc --> (UC18)

@enduml do ano passado