@startuml
skinparam classAttributeIconSize 0
hide methods

class Administrator{
}

class Nurse{
}

class SNSUser{
}

class Receptionist{
}

class CenterCoordinator{
}

class HealthCareCenter {
}

class DGS {
}

class MassiveVaccinationCenter {
}

class CovidDigitalCertificate {
}

class App{
}

class SMSMessage {
- informationAppointment
- timeRecovery
}

class EmailMessage {
- informationAppointment
- timeRecovery
}

class Vaccine {
- vaccineName
- lot
}

class VaccineType {
- ageGroup
- dose
- vaccineDosage
}

class VaccineTime {
- timeBetweenDose
}

class CheckCenterCapacity {
- centerCapacity
- date
- time
}

class ScheduleVaccine {
- userNumberSNS
- vaccinationCenter
- date
- time
- typeOfVaccine
}

class VaccinationCenter {
  - name
  - address
  - emailAddress
  - phoneNumber
  - faxNumber
  - websiteAddress
  - openingHours
  - closingHours
  - slotDuration
  - maxVaccines
  - coordinator
}

Administrator "*"---"*" Nurse : registers >
Administrator "*"---"1" CenterCoordinator : registers >
Administrator "*"---"1" Receptionist : registers >
Administrator "*"---"*" SNSUser : registers >
Administrator "*"---"*" VaccinationCenter : registers >
Administrator "*"---"*" App : manages >
Administrator "*"---"*" DGS : works for >
SNSUser "1"---"*" App : uses >
VaccinationCenter "1"---"*" App
Nurse "*"---"*" App
Nurse "*"---"*" DGS : works for >
Nurse "*"---"1" Vaccine : administrates >
Nurse "*"---"*" VaccinationCenter : works at >
Receptionist "*"---"*" SNSUser : gives info >
Receptionist "*"---"*" VaccinationCenter : works at >
Receptionist "*"---"*" DGS : works for >
CenterCoordinator "1"--"*" DGS : works for >
DGS "1"--"1" MassiveVaccinationCenter
Vaccine "*"--"1" VaccineType : has >
Vaccine "*"--"1" VaccineTime : has >
App "*"--"1" ScheduleVaccine : does >
App "*"--"1" SMSMessage : sends >
App "*"--"1" HealthCareCenter
App "*"--"1" CovidDigitalCertificate : emits >
App "*"--"1" EmailMessage : sends >
ScheduleVaccine "1"--"1" CheckCenterCapacity



@endum