startuml
skinparam classAttributeIconSize 0
hide methods

class Administrator{
}

class Nurse{
}

class SNSUser{
}

class Receptionist{
}

class CenterCoordinator{
}

class HealthCareCenter {
}

class Company {
- designation
}

class SMSMessage {
- informationAppointment
- timeRecovery
}

class EmailMessage {
- informationAppointment
- timeRecovery
}

class Vaccine {
- vaccineName
- lot
}

class VaccineType {
- ageGroup
- dose
- vaccineDosage
}

class VaccineTime {
- timeBetweenDose
}

class CheckCenterCapacity {
- centerCapacity
- date
- time
}

class ScheduleVaccine {
- userNumberSNS
- vaccinationCenter
- date
- time
- typeOfVaccine
}

class VaccinationCenter {
  - name
  - address
  - emailAddress
  - phoneNumber
  - faxNumber
  - websiteAddress
  - openingHours
  - closingHours
  - slotDuration
  - maxVaccines
  - coordinator
}

Administrator "*"---"*" Nurse : registers >
Administrator "*"---"*" CenterCoordinator : registers >
Administrator "*"---"*" Receptionist : registers >
Administrator "*"---"*" SNSUser : registers >
Administrator "*"---"*" VaccinationCenter : registers >


Company "1"---"*" Administrator : knows >
SNSUser "*"---"1" Company : is client >



Nurse "*"---"*" Vaccine : administrates >
Nurse "*"---"1" VaccinationCenter : works at >

Receptionist "*"---"*" SNSUser : gives info >
Receptionist "*"---"1" VaccinationCenter : works at >

CenterCoordinator "*"--"1" Company : works for >
Vaccine "1"--"1" VaccineType : is of >
Vaccine "*"--"1" VaccineTime : has >

ScheduleVaccine "1"--"*" CheckCenterCapacity : verifies >
HealthCareCenter "*"---"*" Vaccine : stores >
VaccineType "*"--"1" Administrator : created by >
Vaccine "*"--"1" Administrator : created by >

Receptionist "1"--"*" ScheduleVaccine : does >
ScheduleVaccine "1"--"1" EmailMessage : emits >
ScheduleVaccine "1"--"1" SMSMessage : emits >
SNSUser "1"--"*" ScheduleVaccine : does >
Administrator "1"--"*" HealthCareCenter : registers >



@endum