startuml
skinparam classAttributeIconSize 0
hide methods

class Administrator{
}

class Nurse{
}

class SNSUser{
}

class Receptionist{
}

class CenterCoordinator{
}

class HealthCareCenter {
}

class Company {
- designation
}

class MassiveVaccinationCenter {
}

class CovidDigitalCertificate {
}

class App{
}

class SMSMessage {
- informationAppointment
- timeRecovery
}

class EmailMessage {
- informationAppointment
- timeRecovery
}

class Vaccine {
- vaccineName
- lot
}

class VaccineType {
- ageGroup
- dose
- vaccineDosage
}

class VaccineTime {
- timeBetweenDose
}

class CheckCenterCapacity {
- centerCapacity
- date
- time
}

class ScheduleVaccine {
- userNumberSNS
- vaccinationCenter
- date
- time
- typeOfVaccine
}

class VaccinationCenter {
  - name
  - address
  - emailAddress
  - phoneNumber
  - faxNumber
  - websiteAddress
  - openingHours
  - closingHours
  - slotDuration
  - maxVaccines
  - coordinator
}

Administrator "*"---"*" Nurse : registers >
Administrator "*"---"*" CenterCoordinator : registers >
Administrator "*"---"*" Receptionist : registers >
Administrator "*"---"*" SNSUser : registers >
Administrator "*"---"*" VaccinationCenter : registers >

Administrator "*"---"1" App : manages >
Company "1"---"*" Administrator : knows >
SNSUser "*"---"1" Company : is client >

SNSUser "*"---"1" App : uses >
VaccinationCenter "*"---"1" App
Nurse "*"---"1" App

Nurse "*"---"*" Vaccine : administrates >
Nurse "*"---"1" VaccinationCenter : works at >

Receptionist "*"---"*" SNSUser : gives info >
Receptionist "*"---"1" VaccinationCenter : works at >

CenterCoordinator "*"--"1" Company : works for >
Company "1"--"*" MassiveVaccinationCenter : owns >
Vaccine "1"--"1" VaccineType : is of >
Vaccine "*"--"1" VaccineTime : has >

App "1"--"*" ScheduleVaccine : does >
App "1"--"*" SMSMessage : sends >
App "1"--"*" HealthCareCenter : manages >
App "1"--"*" CovidDigitalCertificate : emits >
App "1"--"*" EmailMessage : sends >

ScheduleVaccine "1"--"*" CheckCenterCapacity : verifies >
HealthCareCenter "*"---"*" Vaccine : stores >
VaccineType "*"--"1" Administrator : created by >
Vaccine "*"--"1" Administrator : created by >



@endum