@startuml
skinparam classAttributeIconSize 0
left to right direction

class RegisterSNSUserUI{
SpecifyNewSNSUserController ctrl
}
class RegisterSNSUserController{
 Company company
 SNSUser snsu
 +createSNSUser(name, address, sex, phoneNumber, \nemail, birthDate, SNSNumber, citizenCardNumber)
 +saveSNSUser()
 +showSNSUser()
}
class SNSUserStore{
List<SNSUser> snsUserList
+createSNSUser(name, address, sex, phoneNumber, \nemail, birthDate, SNSNumber, citizenCardNumber)
+saveSNSUser(snsu)
+validateSNSUser(snsu)
+getSNSUserList()

}
class Company{
 SNSUserStore snsUserStore
 AuthFacade authFacade
 +getSNSUserStore()
 +getAuthFacade()
}

class SNSUser{
 - name
 - email
 - address
 - phoneNumber
 - gender
 - birthDate
 - SNSNumber
 - citizenCardNumber
}

class AuthFacade{
 +addUserWithRole(name, email, pwd, roleId)
}

class SNSUserMapper{
 +toDTO(snsu)
 +toDTOList(snsul)
}

class SNSUserDTO{
   - name
   - email
   - address
   - phoneNumber
   - gender
   - birthDate
   - SNSNumber
   - citizenCardNumber
}


RegisterSNSUserUI ..> RegisterSNSUserController
Company "1"-->"*" SNSUserStore : has a >
SNSUserStore "1"--"*" SNSUser : keeps info >
RegisterSNSUserController ..> Company
RegisterSNSUserController ..> SNSUserStore
RegisterSNSUserController ..> SNSUser
Company -- AuthFacade : registers SNSUser >
RegisterSNSUserController ..> SNSUserMapper
RegisterSNSUserController ..> SNSUserDTO
SNSUserMapper ..> SNSUserDTO
SNSUserMapper ..> SNSUser

@enduml