@startuml
skinparam classAttributeIconSize 0
left to right direction

class SNSUserUI{}
class SpecifyNewSNSUserController{}
class SNSUserStore{}
class Company{}
class SNSUser{}
class AuthFacade{}


SNSUserUI ..> SpecifyNewSNSUserController
Company "1"-->"*" SNSUserStore : has a >
SNSUserStore "1"-->"*" SNSUser : keeps info >
SpecifyNewSNSUserController ..> Company
SpecifyNewSNSUserController ..> SNSUserStore
SpecifyNewSNSUserController ..> SNSUser
Company -- AuthFacade : registers SNSUser >

@enduml