@startuml

autonumber
actor "Administrator" as adm
participant ":System" as sys

activate adm
adm -> sys : starts registering an Employee

activate sys
sys --> adm : requests role
deactivate sys

adm -> sys : selects role

activate sys
sys --> adm : requests data(name, email, address, phoneNumber, citizenCardNumber)
deactivate sys

adm -> sys : types requested data

activate sys
sys --> adm : shows the data and requests confirmation
deactivate sys

adm -> sys : confirms the data

activate sys
sys --> adm : informs operation success
deactivate sys



deactivate adm
@enduml