@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Counter {
  -counter
}

class RegisterArrivalUI {
  -vaccinationCenter
  -SNSUserNumber
}

class Main {
-time
}

class VaccinationRecord{
}

class ReceptionistUI{
}

RegisterArrivalUI "1" -- "*" Counter : updates >
Counter "*" -- "1" VaccinationRecord : gets information from <
Main "1" -- "1" VaccinationRecord : calls at certain hour >
Main "1" -- "*" ReceptionistUI : gives access to >
ReceptionistUI "*" -- "*" RegisterArrivalUI : operates >



@endumll