@startuml
autonumber
actor "<Automatic> Timer/Clock"  as OE

activate OE
OE -> ":System" : requests configuration file for specified hour
activate ":System"
":System" --> OE : transmits the data requested
deactivate ":System"

OE -> ":System" : asks to record daily the total number of vaccinated people
":System" --> OE : executes what's asked of the class
deactivate ":System"


deactivate OE

@enduml