@startuml
'https://plantuml.com/class-diagram

hide empty members
class DGS{
}

class Timer{
}

class VaccinationsperCenter{
-centername
-count
}

class Company{
}

class VaccinationRecord{
-date
-centername
-count
}



DGS "1" - "1" Timer: runs >
Timer "1" - "1" VaccinationRecord: creates >
Company "1" - "1*" WaitingRoomStore: has >
WaitingRoomStore "1" - "1" VaccinationsperCenter : belongs to <
VaccinationRecord "1" -- "* " VaccinationsperCenter: gets >ll