@startuml


class Main{
+main()
}

class App{
+getProperties()
+getTimerHours()
}

class VaccinationRecord{
-date
-WaitingRoomList
-vaccinespercenter
+run()
}

class Scheduler{

}


abstract class TimerTask{
+run()
}

class Runnable{
+run()
}

class Company{
+getWaitingRoomStore()
}

class WaitingRoomStore{
-count
+vaccinationsperCenter()
}

class vaccinationsperCenter{
-count
}

class VaccinationCenter{
-vaccinationcenter
}





Main --> App : executes
App --> Scheduler : executes
Scheduler ..> VaccinationRecord
VaccinationRecord ..> Company
Company "1" --> "1" WaitingRoomStore : uses >
WaitingRoomStore --> VaccinationCenter : knows >
VaccinationCenter "1" --> "1" Schedule : has >
WaitingRoomStore --> vaccinationsperCenter : knows >
VaccinationRecord ..> vaccinationsperCenter
VaccinationRecord ..> WaitingRoomStore
VaccinationRecord ..> VaccinationCenter
TimerTask --> Runnable : implements >
Scheduler --> TimerTask : extends >
@enduml