@startuml
skinparam classAttributeIconSize 0

class Main{
+TimerTask
}

class ReceptionistUI{
+RegisterArrivalUI
}

class VaccinationRecord{
+Counter
+VaccinationCenterStore
}

class VaccinationCenterStore{
+getVaccinationCenter();
}

Main ..> VaccinationRecord
Main ..> Menu
Menu ..> ReceptionistUI
ReceptionistUI ..> RegisterArrivalUI
RegisterArrivalUI --> VaccinationRecord
VaccinationRecord ..> VaccinationCenterStore
VaccinationRecord ..> Counter


@enduml