@startuml

class SNSUser{}
class VaccineType{
 - ageGroup
 - dose
 - vaccineDosage
}
class Vaccine{}
class Admin{}
class HealthCareCenter{}
class ARS{}
class AGES{}
class VaccinationCenter{
  - name
  - address
  - emailAddress
  - phoneNumber
  - faxNumber
  - websiteAddress
  - openingHours
  - closingHours
  - slotDuration
  - maxVaccines
  - coordinator
}
class ScheduleVaccine{
- userNumberSNS
- vaccinationCenter
- date
- time
- typeOfVaccine
}
class DGS{}
class Nurse{}
class CovidDigitalCertificate{}
class Receptionist{}
class Vaccination{}
class DGS{}
class PerformanceAnalysis{}
class Report{}


Admin "1"---"1" CenterCoordinator : registers >
Admin "1"---"*" SNSUser : registers >
Admin "1"---"*" Vaccine : manages >
SNSUser "*"---"1" Vaccination : administered on <
SNSUser "*"---"1" CovidDigitalCertificate : asks for >
SNSUser "*"---"1" ScheduleVaccine : does >
Nurse "*"---"*" CovidDigitalCertificate : isses >
Nurse "*"---"*" Vaccination : performs >
Nurse "*"---"*" VaccineType : confirms >
Vaccination "1"---"1" ScheduleVaccine : fulfilling >
ScheduleVaccine "1"---"*" VaccineType : for taking >
Vaccine "*"---"*" VaccineType : depends on >
VaccinationCenter "*"---"*" Vaccine : administers >
VaccinationCenter "*"---"*" HealthCareCenter : is a <
VaccinationCenter "*"---"1" CenterCoordinator : has a >
DGS "1"---"*" Admin : employs >
DGS "1"---"*" VaccinationCenter : owns >
DGS "1"---"*" SNSUser : is registered on <
HealthCareCenter "*"---"1" ARS : associated with >
HealthCareCenter "*"---"1" AGES : associated with >
Receptionist "*"---"*" VaccinationCenter : works at >
CenterCoordinator "1"---"*" PerformanceAnalysis : makes >
CenterCoordinator "1"---"*" Report : generates <
Report "*"---"*" PerformanceAnalysis : about >
Receptionist "*"---"1" DGS : works for <


@enduml