@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Receptionist" as USER

activate USER
USER -> ":System" : starts vaccine scheduling
activate ":System"

":System" --> USER : requests data (SNS user number, Vaccination center, Hour of vaccination, Type of Vaccine, Phone number)
deactivate ":System"
USER -> ":System" : types requested data
activate ":System"
":System" --> USER : shows the data and requests a confirmation
deactivate ":System"

USER -> ":System" : confirms the data
activate ":System"
":System" --> USER : informs operation success
deactivate ":System"
@enduml