@startuml
autonumber
actor "Admin" as rcp

activate rcp
rcp -> ":System" : starts operation of asking for list of employees with a given role
activate ":System"
":System" --> rcp : requests role (Nurse, Receptionist, Center Coordinator)
deactivate ":System"

rcp -> ":System" : types requested data
activate ":System"
":System" --> rcp : shows the list of employees with chosen role
deactivate ":System"

deactivate rcp

@endum