@startuml
skinparam classAttributeIconSize 0
left to right direction

class RegisterEmployeeTypeUI{
SpecifyNewEmployeeController ctrl
}

class SpecifyNewEmployeeController{
Company company
VaccineType vt
+createVaccineType(code, designation, whoId)
+validateVaccineType(vt)
}

class Employee{
   -Name
   -E-mail
   - Address
   - Phone Number
   - Citizen Card Number
   - Employee ID
   - Role
}

class Company{
VaccineTypeStore vaccineTypeStore
+addVaccineType(vt)
}

class EmployeeStore{}

RegisterEmployeeTypeUI ..> SpecifyNewEmployeeController
Company "1"--"*" EmployeeStore : has a >
EmployeeStore "1"--"*"Employee : keeps info >
SpecifyNewEmployeeController ..> Company
SpecifyNewEmployeeController ..> EmployeeStore
SpecifyNewEmployeeController ..> Employee



@enduml