@startuml
autonumber
'hide footbox
actor "Administrator" as ADM

participant ": EmployeeUI" as UI
participant ": SpecifyNewEmployeeController" as CTRL
participant ": Company" as COMP
participant ": EmployeeStore" as STORE
participant "Employee" as EMP
participant ": AuthFacade" as auth



activate ADM
ADM -> UI : asks to create a new Employee
activate UI
UI --> ADM : requests data ( Name, E-mail, Address, Phone Number, Citizen Card Numbe, Employee ID, Role)
deactivate UI

ADM -> UI : types requested data
activate UI

UI -> CTRL : ctrl.createEmployee(askName(), askEmail(), askAddress(), askPhoneNumber(), askCitizenCard(), askEmployeeID())

activate CTRL
CTRL -> EMP : emp = name, email, address, phoneNumber, citizenCardNumber, employeeID, role)
activate EMP
deactivate EMP

CTRL -> CTRL : validateEmployee(emp)




UI --> ADM : displays data waiting for confirmation
deactivate CTRL
deactivate UI

ADM -> UI : confirms data of Employee
activate UI


UI -> CTRL : ctrl.addEmployee()
activate CTRL


CTRL -> COMP : company.addEmployee(e)
deactivate CTRL
activate COMP



COMP -> STORE : employeeStore.addEmployee(e)
activate STORE
deactivate STORE

COMP -> auth  : authFacade.addUserWithRole(e.getName(), e.getEmail(),generateRandomPassword(), e.getRole())
activate auth
deactivate auth
deactivate COMP


UI --> ADM : informs success
deactivate UI
deactivate ADM

@enduml